### ISSUE TITLE
Unity won't display the Spout Output from KodeLife

### ISSUE THREAD

**Issue by masllsam** [keijiro/Beta#1]
Hi, I don't know why but the Kodelife Texture is not loaded on the walls. It stays dark, but also doesn't display any error message.

**Comment by keijiro** [comment]
- First of all, did you enable the Spout output on the KodeLife side?
- Then you have to increase intensity level using a MIDI controller (CC 22 and 23).

**Comment by masllsam** [comment]
Yes I activated spout output. And no I didnt increase kodelife value. Thx
for the input. Will try asap! Great Job!

Keijiro Takahashi <notifications@github.com> schrieb am Mi., 22. Apr. 2020,
03:11:

**Comment by geslotencirkel** [comment]
I didn't have this issue!

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if it still reproduces.
