### ISSUE TITLE
FOV object bound to CC#0 not working in published player in 2020.1.0b3 // fov vs fieldOfView  + fix

### ISSUE THREAD

**Issue by geslotencirkel** [keijiro/Beta#2]
playing around and decided to publish an edit of the project through 2020.1.0b3 (yeah i know..) and everything is fine except CC#0 won't work. So I checked the bindings and saw that the Property drop down for Camera has another option called fieldOfView. Selected this one and everything works in a published player (windows standalone player)

**Comment by keijiro** [comment]
This issue was fixed in 2019.3 branch.

https://github.com/keijiro/Beta/tree/2019.3

The master branch is kept intact for recording purpose.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
